PhotoContest.App/ViewModels/ActiveViewModel.cs
using System;
using System.Collections.Generic;


namespace PhotoContest.App.ViewModels
{
    public class ActiveViewModel
    {
        public IEnumerable<ContestViewModel> ActiveContests { get; set; }

        public IEnumerable<NotificationViewModel> Notifications { get; set; }
        
    }
}

PhotoContest.App/ViewModels/ContestViewModel.cs
namespace PhotoContest.App.ViewModels
{
    using System;
    using PhotoContest.Models;
    using Common.Mappings;
    using PhotoContest.Models.Enums;
    using System.Collections.Generic;
    using AutoMapper;

    public class ContestViewModel : IMapFrom<Contest>, IHaveCustomMappings
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string CreatorId { get; set; }

        public ContestStatus Status { get; set; }

        public ParticipationStrategy ParticipationStrategy { get; set; }

        public DateTime DateCreated { get; set; }

        public DateTime? DateEnd { get; set; }

        public int? MaximumParticipants { get; set; }

        public DeadLineStrategy DeadLineStrategy { get; set; }

        public bool IsExpired { get; set; }

        public bool IsFull { get; set; }

        public IEnumerable<MinifiedUserViewModel> Participants { get; set; }

        public void CreateMappings(IConfiguration configuration)
        {
            configuration.CreateMap<Contest, ContestViewModel>()
                .ForMember(x => x.IsExpired, cnf => cnf.MapFrom(c => c.DateEnd == null ? false :  c.DateEnd >= DateTime.Now))
                .ForMember(x => x.IsFull, cnf => cnf.MapFrom(c => c.MaximumParticipants == null ? false : c.Participants.Count >= c.MaximumParticipants));
        }
    }
}

PhotoContest.App/Controllers/ContestsController.cs
using System.Collections.Generic;
using Microsoft.AspNet.Identity;

namespace PhotoContest.App.Controllers
{
    using System;
    using System.Web.Mvc;
    using Data.UnitOfWork;
    using System.Linq;
    using AutoMapper.QueryableExtensions;
    using ViewModels;
    using AutoMapper;
    using BindingModels;
    using PhotoContest.Models;
    using System.Data.Entity;
    using PhotoContest.Models.Enums;
    using System.Collections.Generic;

    public class ContestsController : BaseController
    {
        public ContestsController(IPhotoContestData data)
            : base(data)
        {
        }

        [AllowAnonymous]
        public ActionResult Active()
        {
            var contests = this.Data.Contests
                .All()
                .Where(x => x.Status == ContestStatus.Active);

            foreach (var contest in contests)
            {
                contest.Status = this.UpdateContestStatus(contest);
            }

            this.Data.SaveChanges();

            var activeContests = contests
                .Where(x => x.Status == ContestStatus.Active)
                .Project()
                .To<ContestViewModel>();

            return this.View(activeContests);

        }

        [AllowAnonymous]
        public ActionResult Past()
        {
            var pastContests = this.Data.Contests
                .All()
                .Where(x => x.Status == ContestStatus.Finished || x.Status == ContestStatus.Dismissed)
                .OrderByDescending(x => x.DateEnd)
                .Project()
                .To<ContestViewModel>();

            return View(pastContests);
        }

        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            var contest = this.Data.Contests
                .All()
                .Include(x => x.Photos)
                .Include(x => x.Participants)
                .Include(x => x.Winners)
                .FirstOrDefault(x => x.Id == id);

            if (contest == null)
            {
                return this.HttpNotFound();
            }

            if (this.User.Identity.IsAuthenticated)
            {
                ViewBag.HasUserPartisipate = this.HasParticipateInContest(id, this.UserProfile);
            }

            var contestViewModel = Mapper.Map<ContestDetailsViewModel>(contest);
            if (contest.Status == ContestStatus.Finished)
            {
                contestViewModel.Photos.OrderByDescending(x => x.Votes);
            }
            else
            {
                contestViewModel.Photos.OrderByDescending(x => x.DateAdded);
            }

            return View(contestViewModel);
        }

        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContestBindingModel model)
        {
            if (model != null && this.ModelState.IsValid)
            {
                var contest = Mapper.Map<Contest>(model);
                contest.DateCreated = DateTime.Now;
                contest.Creator = this.UserProfile;
                contest.NumberOfPrices = model.NumberOfPrices ?? 1;
                this.Data.Contests.Add(contest);
                this.Data.SaveChanges();

                return this.RedirectToAction("Details", new { id = contest.Id });
            }

            return this.View(model);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Edit(int id)
        {
            var contest = this.Data.Contests
                .All()
                .Where(x => x.Id == id)
                .Project()
                .To<ContestBindingModel>()
                .FirstOrDefault();

            if (contest == null)
            {
                return this.HttpNotFound();
            }
            if (contest.CreatorId != this.UserProfile.Id)
            {
                return new HttpUnauthorizedResult("Have to be contest owner to edit it.");
            }

            return this.View(contest);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ContestBindingModel model)
        {
            var contest = this.Data.Contests.GetById(id);
            if (contest == null)
            {
                return this.HttpNotFound();
            }
            if (contest.CreatorId != this.UserProfile.Id)
            {
                return new HttpUnauthorizedResult("Have to be contest owner to edit it.");
            }
            contest.Title = model.Title;
            contest.Description = model.Description;
            contest.DateEnd = model.DateEnd;
            contest.MaximumParticipants = model.MaximumParticipants;
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", new { id = contest.Id });
        }

        [Authorize]
        public ActionResult Created()
        {
            var userId = this.UserProfile.Id;
            var ownContests = this.Data.Contests
                .All()
                .Where(x => x.CreatorId == userId && (x.DateCreated < x.DateEnd || x.DateEnd == null))
                .Project()
                .To<ContestViewModel>();

            return this.View(ownContests);
        }

        [Authorize]
        public ActionResult Participate(int contestId)
        {
            var contest = this.Data.Contests.GetById(contestId);

            if (contest == null)
            {
                return this.HttpNotFound();
            }

            bool isInvited = contest.InvitedUsers.Contains(this.UserProfile);

            if (contest.ParticipationStrategy == ParticipationStrategy.Closed && !isInvited)
            {
                return new HttpUnauthorizedResult();
            }

            if (this.HasParticipateInContest(contestId, this.UserProfile))
            {
                throw new InvalidOperationException("You already participate in this contest.");
            }

            contest.Participants.Add(this.UserProfile);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", new { id = contestId });
        }

        public ActionResult Dismiss(int id)
        {
            var contest = this.Data.Contests.GetById(id);

            if (contest == null)
            {
                return this.HttpNotFound();
            }
            if (contest.CreatorId != this.UserProfile.Id)
            {
                return new HttpUnauthorizedResult();
            }

            contest.Status = ContestStatus.Dismissed;
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", new { id = contest.Id });
        }

        public ActionResult Finalize(int id)
        {
            var contest = this.Data.Contests
                .All()
                .Where(x => x.Id == id)
                .Include(x => x.Photos)
                .FirstOrDefault();

            if (contest == null)
            {
                return this.HttpNotFound();
            }
            if (contest.CreatorId != this.UserProfile.Id)
            {
                return new HttpUnauthorizedResult();
            }

            var winners =
                contest.Photos
                .OrderByDescending(p => p.Votes.Count)
                .Take(contest.NumberOfPrices)
                .Select(p => p.Author)
                .ToList();

            foreach (var winner in winners)
            {
                contest.Winners.Add(winner);
            }

            contest.Status = ContestStatus.Finished;
            this.Data.SaveChanges();

            //Get Winners
            //Send Notifications to participants for the end of the contest 

            return this.RedirectToAction("Details", new { id = id });
        }

        private bool HasParticipateInContest(int contestId, User user)
        {
            return user.ContestsParticipateIn.Any(x => x.Id == contestId);
        }

        private ContestStatus UpdateContestStatus(Contest contest)
        {
            if (contest.Status != ContestStatus.Dismissed && contest.Status != ContestStatus.Finished)
            {
                if (contest.Status != ContestStatus.Dismissed && contest.Status != ContestStatus.Finished)
                {
                    if (contest.DeadLineStrategy == DeadLineStrategy.ByTime && contest.DateEnd <= DateTime.Now)
                    {
                        return ContestStatus.UploadClosed;
                    }
                    if (contest.DeadLineStrategy == DeadLineStrategy.ByNumberOfParticipants && contest.Participants.Count >= contest.MaximumParticipants)
                    {
                        return ContestStatus.ParticipationClosed;
                    }
                }
            }

            return contest.Status;
        }
    }
}


PhotoContest.App/Controllers/ImageController.cs
namespace PhotoContest.App.Controllers
{
    using AutoMapper;
    using Data.Repository;
    using Data.UnitOfWork;
    using PhotoContest.Models;
    using System;
    using System.Data.Entity;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using ViewModels;

    [Authorize]
    public class ImageController : BaseController
    {
        public ImageController(IPhotoContestData data) : base(data)
        {
        }

        public ActionResult UploadImage()
        {
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UploadImage(int contestId, HttpPostedFileBase image)
        {
            var authorName = this.UserProfile.UserName;
            var path = DropBoxRepository.Upload(image.FileName, authorName, image.InputStream);
            var photo = new Photo
            {
                Name = image.FileName,
                Path = path,
                AuthorId = this.UserProfile.Id,
                ContestId = contestId, 
                DateAdded = DateTime.Now,
            };
            this.Data.Photos.Add(photo);
            this.Data.SaveChanges();

            return this.RedirectToAction("Details", "Contests", new { id = contestId });
        }

        [AllowAnonymous]
        public ActionResult GetImage(int photoId)
        {
            var image = this.Data.Photos
                .All()
                .Include(x => x.Votes)
                .FirstOrDefault(x => x.Id == photoId);

            if (image == null)
            {
                return HttpNotFound();
            }

            var imageViewModel = Mapper.Map<PhotoViewModel>(image);

            if (this.User.Identity.IsAuthenticated)
            {
                imageViewModel.UserHasVoted = image.Votes.Any(x => x.UserId == this.UserProfile.Id);
            }

            imageViewModel.Url = DropBoxRepository.Download(imageViewModel.Path);
            return this.PartialView("_GetImagePartial", imageViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Vote(int photoId, int contestId)
        {
            var photo = this.Data.Photos
                .All()
                .FirstOrDefault(x => x.Id == photoId);

            if (photo != null)
            {
                var userHasVoted = photo.Votes.Any(x => x.UserId == this.UserProfile.Id);
                if (!userHasVoted)
                {
                    this.Data.Votes.Add(new Vote
                    {
                        PhotoId = photoId,
                        UserId = this.UserProfile.Id,
                        ContestId = contestId,
                        Value = 1
                    });

                    this.Data.SaveChanges();
                }

                var votesCout = photo.Votes.Sum(x => x.Value);
                return this.Content(votesCout.ToString());
            }

            return new EmptyResult();
        }
    }
}

PhotoContest.App/Controllers/NotificationsController.cs
using System;
using System.Web.UI.WebControls;

namespace PhotoContest.App.Controllers
{
    using System.Web.Mvc;
    using Microsoft.AspNet.SignalR;
    using Hub;
    using System.Collections.Generic;
    using System.Linq;
    using Data.UnitOfWork;
    using AutoMapper.QueryableExtensions;
    using ViewModels;
    using Newtonsoft.Json;
    using PhotoContest.Models;

    public class NotificationsController : BaseController
    {

        public NotificationsController(IPhotoContestData data) : base(data)
        {
        }

        public ActionResult SendNotification(string notification)
        {
            var hubContext = GlobalHost.ConnectionManager.GetHubContext<NotificationsHub>();
            hubContext.Clients.All.receiveNotification(notification);

            return new EmptyResult();
            //return this.Content("Notification sent.<br />");
        }

        public ActionResult SearchUser(string query)
        {
            if (!string.IsNullOrEmpty(query))
            {
                var usersResult = this.Data.Users
                   .All()
                   .Where(x => x.UserName.StartsWith(query))
                   .OrderBy(x => x.UserName)
                   .Project()
                   .To<MinifiedUserViewModel>();

                //var jsonResult = JsonConvert.SerializeObject(usersResult).ToString();

                return this.Json(usersResult, JsonRequestBehavior.AllowGet);
            }

            return new EmptyResult();
        }

        public ActionResult Invite(string senderName, string receiverName, int contestId)
        {
            var contest = this.Data.Contests.GetById(contestId);

            if (contest == null)
            {
                return this.HttpNotFound();
            }

            if (contest.Participants.Any(x => x.UserName == receiverName))
            {
                throw new InvalidOperationException("User already participates in this contest.");
            }


            var invitedUser = this.Data.Users.All().FirstOrDefault(x => x.UserName == receiverName);
            if (invitedUser == null)
            {
                return this.HttpNotFound();
            }


            contest.Participants.Add(invitedUser);

            var invitation = new Notification
            {
                ContestId = contestId,
                IsRead = false,
                Sender = this.Data.Users.All().FirstOrDefault(x => x.UserName == senderName),
                Receiver = this.Data.Users.All().FirstOrDefault(x => x.UserName == receiverName),
                Message = "You have been invited to participate in contest"
            };

            invitedUser.ReceivedNotifications.Add(invitation);
            //this.Data.Notifications.Add(invitation);
            this.Data.SaveChanges();

            return new EmptyResult();
        }

        [System.Web.Mvc.Authorize]
        public ActionResult ShowNotifications()
        {
            var notifications = this.UserProfile.ReceivedNotifications
                .Where(x => !x.IsRead)
                .AsQueryable()
                .Project()
                .To<NotificationViewModel>()
                .ToList();

            return this.PartialView("_NotificationsPartial", notifications);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult ReadNotification(int notificationId)
        {
            var notification = this.Data.Notifications.GetById(notificationId);

            if (notification == null)
            {
                return this.HttpNotFound();
            }

            notification.IsRead = true;
            this.Data.SaveChanges();

            return this.Content("");
        }
    }
}

PhotoContest.App/Views/Contests/Active.cshtml
@using Microsoft.AspNet.Identity
@model IEnumerable<PhotoContest.App.ViewModels.ContestViewModel>
@{
    ViewBag.Title = "Active Contest";
}

@if (Request.IsAuthenticated)
{
    @Html.Action("ShowNotifications", "Notifications")
}

<div class="row">
    @Html.DisplayFor(x => x)
</div>

PhotoContest.App/Views/Contests/Created.cshtml
@model IEnumerable<PhotoContest.App.ViewModels.ContestViewModel>

@{
    ViewBag.Title = "Own Contests";
}

<div class="jumbotron">
    <h2>@ViewBag.Title</h2>
    <h2>Welcome to Pinarcor Photo Contest Site!</h2>
    <h3>Give us Your best photo and win prizes!</h3>
</div>

@{
    foreach (var contest in Model)
    {
        <div class="col-md-4">
            <h3>@contest.Title</h3>
            <p>Created on: @String.Format("{0:M/d/yyyy}", @contest.DateCreated)</p>
            <p>End: @String.Format("{0:M/d/yyyy}", @contest.DateEnd)</p>
            <p>Participation Strategy: @contest.ParticipationStrategy</p>
            @Html.ActionLink("Edit", "Edit", "Contests", new { id = contest.Id } ,new { @class=  "btn btn-info btn-sm" })
            @Html.ActionLink("Finalize", "Finalize", "Contests", new { id = contest.Id } ,new { @class = "btn btn-warning btn-sm" })
            @Html.ActionLink("Dismiss", "Dismiss", "Contests", new { id = contest.Id } ,new { @class = "btn btn-danger btn-sm" })
            @Html.ActionLink("Details", "Details", "Contests", new { id = contest.Id }, new { @class = "btn btn-primary" })
        </div>
    }
}

PhotoContest.App/Views/Contests/Details.cshtml
@using Microsoft.AspNet.Identity
@using PhotoContest.Models.Enums
@using Microsoft.AspNet.Identity
@model PhotoContest.App.ViewModels.ContestDetailsViewModel
@{
    ViewBag.Title = "Details";
}
<h3>@Model.Title</h3>
@{
    if (Model.Status == ContestStatus.Dismissed)
    {
        <h4> Dismissed </h4>
    }
}
<div class="row">
    <div class="col-lg-4">
        <p>@Html.DisplayNameFor(x => x.Description): @Html.DisplayFor(x => x.Description)</p>
        <p>@Html.DisplayNameFor(x => x.Creator): @Html.DisplayFor(x => x.Creator)</p>
        <p>@Html.DisplayNameFor(x => x.DateCreated): @Html.DisplayFor(x => x.DateCreated)</p>
        @{
            if (Model.DeadLineStrategy == DeadLineStrategy.ByTime)
            {
                <p>End: @String.Format("{0:M/d/yyyy}", @Model.DateEnd)</p>
            }
            else
            {
                <p> Participants: @Model.Participants.Count() / @Model.MaximumParticipants</p>
            }
        }
    </div>
    <div class="col-lg-4 pull-right">
        @{
            if (Model.Status == ContestStatus.Finished)
            {
                Html.RenderPartial("_WinnersPartial", Model.Winners);
            }
            else
            {
                Html.RenderPartial("_ParticipantsPartial", Model.Participants);
            }
        }
    </div>
</div>
@if (Request.IsAuthenticated &&
                Model.Creator == this.User.Identity.Name &&
                Model.ParticipationStrategy == ParticipationStrategy.Closed)
{
    @Html.Partial("_InvitationPartial")
}
<div class="row">
    @{
        if (Request.IsAuthenticated &&
            this.User.Identity.GetUserId() == Model.CreatorId &&
            Model.Status == ContestStatus.Active)
        {
            <hr />
            @Html.ActionLink("Edit", "Edit", "Contests", new { id = Model.Id }, new { @class = "btn btn-info btn" });
            @Html.ActionLink("Finalize", "Finalize", "Contests", new { id = Model.Id }, new { @class = "btn btn-warning btn" });
            @Html.ActionLink("Dismiss", "Dismiss", "Contests", new { id = Model.Id }, new { @class = "btn btn-danger btn" });
        }

        if (Request.IsAuthenticated
        && Model.ParticipationStrategy == ParticipationStrategy.Open
        && !(Model.Participants.Any(x => x.Id == this.User.Identity.GetUserId()))
        && Model.Status == ContestStatus.Active
        && Model.CreatorId != this.User.Identity.GetUserId())
        {
            @Html.ActionLink("Participate", "Participate", "Contests", new { contestId = @Model.Id }, new { @class = "btn btn-success btn-sm" })
        }

    }
</div>
@if (Request.IsAuthenticated &&
                this.ViewBag.HasUserPartisipate &&
                (Model.Status == ContestStatus.Active || Model.Status == ContestStatus.ParticipationClosed))
{
    <h4> Upload Your photo </h4>

    using (Html.BeginForm("UploadImage", "Image", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.TextBox("image", new { }, new { type = "file" })
        <input type="hidden" value="@Model.Id" name="contestId" />
        <input type="submit" class="btn btn-primary" value="Upload" />
    }
}
@if (Model.Status == ContestStatus.Finished)
{
    <div class="row">
        <div class="col-lg-12">
            <div id="photos" class="panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title" style="text-align: center; font-size: 20px;"> Final Standing </h2>
                </div>
                <div class="panel-body">

                    @if (Model.Photos.Any())
                    {
                        foreach (var photo in Model.Photos)
                        {
                                @Html.Action("GetImage", "Image", new { photoId = photo.Id });
                        }
                    }
                    else
                    {
                        <span> No photos yet. </span>
                    }

                </div>
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-lg-12">
            <div id="photos" class="panel-success">
                <div class="panel-heading">
                    <h2 class="panel-title" style="text-align: center; font-size: 20px;">Photos</h2>
                </div>
                <div class="panel-body">

                    @if (Model.Photos.Any())
                    {
                        foreach (var photo in Model.Photos)
                        {
                            @Html.Action("GetImage", "Image", new { photoId = photo.Id });
                        }
                    }
                    else
                    {
                        <span> No photos yet. </span>
                    }

                </div>
            </div>
        </div>
    </div>
}


@section scripts
{
    <script>
        function onVoteSuccess(id) {
            var buttonDiv = $("#vote-button-" + id);
            buttonDiv.empty();
        }

        $(document).ready(function() {

            function inviteUser(senderName, receiverName, contestId) {
                $.ajax({
                    url: '/Notifications/Invite',
                    type: "post",
                    dataType: 'text',
                    data: {
                        senderName: senderName,
                        receiverName: receiverName,
                        contestId: contestId
                    },
                    success: function(data) {
                        $(receiverName).remove();
                    },
                    error: function(data) {

                    }
                });
            }

            $('#search').keyup(function(e) {
                var searchQuery = $('#search').val();
                $.getJSON("/Notifications/SearchUser", {
                    query: searchQuery
                },
                    function(data) {
                        var div = $('#users');
                        var ul = $('<ul>');
                        $(div).html('');
                        $.each(data, function(i, user) {
                            var li = $('<li>', { id: user.Id, text: user.UserName, class: "invites" });
                            var button = $('<input>', { type: "button", id: user.UserName, value: "Invite" });
                            $(button).click(function() {
                                var owner = $("#userName").text();

                                inviteUser(owner, user.UserName, @Model.Id);
                            });
                            button.appendTo(li);
                            li.appendTo(ul);

                        });
                        ul.appendTo(div);

                        @*$('input[type="button"][value="Invite"]').click(function () {
                            inviteUser("iii", "sss", @Model.Id);
                        });*@
                    });

            });
        });

    </script>
}

PhotoContest.App/Views/Contests/Edit.cshtml
@model PhotoContest.App.BindingModels.ContestBindingModel

@{
    ViewBag.Title = "Update Contest";
}

<div class="col-md-offset-4">
    <h3>@ViewBag.Title</h3>
</div>
<div class="row">
    <div class="col-md-10">
        @using (Html.BeginForm("Edit", "Contests", FormMethod.Post, new { @class = "form-horizontal" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-group">
                @Html.LabelFor(x => x.Title, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", id = "Title" })
                    @Html.ValidationMessageFor(x => x.Title, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.Description, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.TextBoxFor(x => x.Description, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Description, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.RewardStrategy, new { @class = "col-md-4 control-label", Disabled = "true" })
                <div class="col-md-8"></div>
                @Html.EnumDropDownListFor(x => x.RewardStrategy, new { @class = "form-control", id = "reward-strategy", Disabled = "true" })
            </div>
            <div class="form-group" id="number-of-winners"></div>
            <div class="form-group">
                @Html.LabelFor(x => x.DeadLineStrategy, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.EnumDropDownListFor(x => x.DeadLineStrategy, new { @class = "form-control", id = "deadline-strategy", Disabled = "true" })
                </div>
            </div>
            if (Model.DeadLineStrategy == 0)
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.DateEnd, new { @class = "col-md-4 control-label" })
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.DateEnd, new { @class = "form-control", value = Model.DateEnd })
                        @Html.ValidationMessageFor(x => x.DateEnd, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.LabelFor(x => x.MaximumParticipants, new { @class = "col-md-4 control-label" })
                    <div class="col-md-8">
                        @Html.TextBoxFor(x => x.MaximumParticipants, new { @class = "form-control", value = Model.MaximumParticipants })
                        @Html.ValidationMessageFor(x => x.MaximumParticipants, "", new { @class = "text-danger" })
                    </div>
                </div>
            }
            <div class="form-group" id="deadline-container"></div>

            <div class="form-group">
                @Html.LabelFor(x => x.ParticipationStrategy, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.EnumDropDownListFor(x => x.ParticipationStrategy, new { @class = "form-control", Disabled = "true" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(x => x.VotingStrategy, new { @class = "col-md-4 control-label" })
                <div class="col-md-8">
                    @Html.EnumDropDownListFor(x => x.VotingStrategy, new { @class = "form-control", Disabled = "true" })
                </div>
            </div>
            <div class="form-controll">
                <div class="col-md-offset-4">
                    <input type="submit" value="Edit" class="btn btn-primary"/>
                    @Html.ActionLink("Cancel", "Created", "Contests", new { @class = "btn btn-primary"})
                </div>
            </div>
        }
    </div>
</div>

PhotoContest.App/Views/Contests/Finalize.cshtml
@{
    ViewBag.Title = "Finalize";
}

<h2>Finalize</h2>

PhotoContest.App/Views/Contests/FinishedDetails.cshtml
@using PhotoContest.Models.Enums
@model PhotoContest.App.ViewModels.FinishedContestViewModel

<h3>@Model.Title</h3>

@if (Model.Status == ContestStatus.Dismissed)
{
    <h2 class="text-danger"> Dismissed </h2>
}

<div>
    <p>@Html.DisplayNameFor(x => x.Description): @Html.DisplayFor(x => x.Description)</p>
    <p>@Html.DisplayNameFor(x => x.Creator): @Html.DisplayFor(x => x.Creator)</p>
    <p>@Html.DisplayNameFor(x => x.DateCreated): @Html.DisplayFor(x => x.DateCreated)</p>
</div>

<hr />

<div id="photos">
    <h2> Final Standings </h2>

    @{
        if (Model.Photos.Any())
        {
            foreach (var photo in Model.Photos)
            {
                @Html.Action("GetImage", "Image", new { photoId = photo.Id });
            }
        }
        else
        {
            <span> No photos yet. </span>
        }
    }
</div>

PhotoContest.App/Views/Contests/Past.cshtml
@model IEnumerable<PhotoContest.App.ViewModels.ContestViewModel>
@{
    
}
<h2>Past contests</h2>

<div class="row">
    @Html.DisplayFor(x => x)

</div>